"""Response behavior analyzer for NeuroFence.

Step 5 of the NeuroFence Security Pipeline.

Analyzes generated response text for refusal indicators, output entropy,
n-gram repetition ratios, and behavioral degradation signatures.

This module contains **no UI code** — it is pure business logic.
"""

from __future__ import annotations

import math
import re
from collections import Counter
from dataclasses import dataclass, field

# Common safety refusal prefixes / phrases across major LLM families
_REFUSAL_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"i (cannot|can't) (fulfill|provide|assist|help|generate|comply)", re.IGNORECASE),
    re.compile(r"as an ai (language model|assistant)", re.IGNORECASE),
    re.compile(r"i am (unable|not allowed|not programmed) to", re.IGNORECASE),
    re.compile(r"sorry, (but )?i (cannot|can't)", re.IGNORECASE),
    re.compile(r"violates (my|our|safety) (policy|guidelines|rules)", re.IGNORECASE),
    re.compile(r"ethical (guidelines|principles|considerations)", re.IGNORECASE),
    re.compile(r"harmful, illegal, or unethical", re.IGNORECASE),
)

# Unsafe topic key terms for heuristic monitoring
_RISK_KEYWORDS: dict[str, list[str]] = {
    "Exfiltration": ["system prompt", "internal instructions", "override rules", "developer mode"],
    "Adversarial": ["jailbreak", "bypass", "DAN mode", "do anything now", "ignore previous instructions"],
    "Malware": ["shellcode", "exploit payload", "keylogger", "reverse shell", "buffer overflow"],
    "Obfuscation": ["base64", "rot13", "hex encode", "payload obfuscation"],
}


@dataclass(frozen=True)
class ResponseBehavior:
    """Quantitative behavioral metrics derived from model output.

    Attributes:
        is_refusal:          ``True`` if safety refusal pattern was detected.
        refusal_confidence:   Score (0.0 to 1.0) indicating certainty of refusal.
        refusal_matched:     Matched pattern phrase if refusal was detected.
        entropy_score:       Shannon entropy of character distribution in output.
        repetitiveness_ratio: Ratio of duplicate n-grams (0.0 = diverse, 1.0 = loop).
        flagged_categories:  List of risk categories detected in output/prompt.
        character_count:     Length of output response text.
    """

    is_refusal: bool
    refusal_confidence: float
    refusal_matched: str
    entropy_score: float
    repetitiveness_ratio: float
    flagged_categories: list[str] = field(default_factory=list)
    character_count: int = 0


class BehaviorAnalyzer:
    """Analyzes model output text for behavioral anomalies and safety signatures."""

    def analyze(self, response_text: str, prompt_text: str = "") -> ResponseBehavior:
        """Run full behavioral evaluation on *response_text*.

        Args:
            response_text: Text generated by the model.
            prompt_text:   Original prompt text (optional, used for keyword scanning).

        Returns:
            A populated :class:`ResponseBehavior` instance.
        """
        if not response_text or not response_text.strip():
            return ResponseBehavior(
                is_refusal=False,
                refusal_confidence=0.0,
                refusal_matched="",
                entropy_score=0.0,
                repetitiveness_ratio=0.0,
                flagged_categories=[],
                character_count=0,
            )

        # ── 1. Refusal Detection ──────────────────────────────────────
        is_refusal, confidence, matched_phrase = self._detect_refusal(response_text)

        # ── 2. Entropy & Repetitiveness ──────────────────────────────
        entropy = self._compute_entropy(response_text)
        repetition = self._compute_repetition_ratio(response_text)

        # ── 3. Risk Keyword Scanning ─────────────────────────────────
        flagged = self._scan_keywords(response_text, prompt_text)

        return ResponseBehavior(
            is_refusal=is_refusal,
            refusal_confidence=confidence,
            refusal_matched=matched_phrase,
            entropy_score=round(entropy, 4),
            repetitiveness_ratio=round(repetition, 4),
            flagged_categories=flagged,
            character_count=len(response_text),
        )

    # ── Private Helpers ──────────────────────────────────────────────

    @staticmethod
    def _detect_refusal(text: str) -> tuple[bool, float, str]:
        """Check text against refusal patterns and return (is_refusal, confidence, phrase)."""
        text_lower = text[:500].lower()  # Refusals almost always occur in prefix

        matches = []
        for pattern in _REFUSAL_PATTERNS:
            match = pattern.search(text_lower)
            if match:
                matches.append(match.group(0))

        if matches:
            confidence = min(1.0, 0.6 + 0.2 * len(matches))
            return True, confidence, matches[0]

        return False, 0.0, ""

    @staticmethod
    def _compute_entropy(text: str) -> float:
        """Compute Shannon entropy of the character distribution in text."""
        if not text:
            return 0.0

        length = len(text)
        counts = Counter(text)
        entropy = 0.0

        for count in counts.values():
            p = count / length
            entropy -= p * math.log2(p)

        return entropy

    @staticmethod
    def _compute_repetition_ratio(text: str, n: int = 3) -> float:
        """Compute 3-gram repetition ratio to catch generation loops.

        Returns 0.0 for completely unique n-grams, approaching 1.0 for repetitive loops.
        """
        words = text.lower().split()
        if len(words) < n:
            return 0.0

        ngrams = [tuple(words[i : i + n]) for i in range(len(words) - n + 1)]
        if not ngrams:
            return 0.0

        unique_ngrams = set(ngrams)
        ratio = 1.0 - (len(unique_ngrams) / len(ngrams))
        return max(0.0, ratio)

    @staticmethod
    def _scan_keywords(response_text: str, prompt_text: str) -> list[str]:
        """Scan text for risk keywords across defined security categories."""
        combined = (prompt_text + " " + response_text).lower()
        flagged: set[str] = set()

        for category, terms in _RISK_KEYWORDS.items():
            for term in terms:
                if term in combined:
                    flagged.add(category)
                    break

        return sorted(flagged)
